version: '3'
services:
  proxy:
    restart: always
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
    depends_on:
      - server
  server:
    image: harryoh/crypto-collector
    build:
      context: .
    restart: unless-stopped
    volumes:
      - .env:/opt/app/.env
    # environment:
    #   - UpbitPeriodSeconds=${UpbitPeriodSeconds}
    #   - BithumbPeriodSeconds=${BithumbPeriodSeconds}
    #   - BybitPeriodSeconds=${BybitPeriodSeconds}
    #   - UsdKrwPeriodSeconds=${UsdKrwPeriodSeconds}
    #   - AlarmPeriodSeconds=${AlarmPeriodSeconds}
    #   - MonitorPeriodSeconds=${MonitorPeriodSeconds}
    #   - AlarmChatID=${AlarmChatID}
    #   - AlarmToken=${AlarmToken}
    #   - MonitorChatID=${MonitorChatID}
    #   - MonitorToken=${MonitorToken}
    # ports:
    #   - 8080:8080
