version: '2'

services:

  server:
    image: harryoh/crypto-collector
    volumes:
      - .env:/opt/app/.env
    # environment:
    #   - UpbitPeriodSeconds=${UpbitPeriodSeconds}
    #   - BithumbPeriodSeconds=${BithumbPeriodSeconds}
    #   - BybitPeriodSeconds=${BybitPeriodSeconds}
    #   - UsdKrwPeriodSeconds=${UsdKrwPeriodSeconds}
    #   - AlarmPeriodSeconds=${AlarmPeriodSeconds}
    #   - MonitorPeriodSeconds=${MonitorPeriodSeconds}
    #   - AlarmChatID=${AlarmChatID}
    #   - AlarmToken=${AlarmToken}
    #   - MonitorChatID=${MonitorChatID}
    #   - MonitorToken=${MonitorToken}
    ports:
      - 8080:8080
