name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Nodejs Packages
      run: cd ui && npm install
    - name: Build UI
      run: cd ui && npm run build
    - name: Build the Docker Image
      # run: docker build . --tag crypto-collector:$(date +%s)
      run: docker build . --tag crypto-collector
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: harryoh/crypto-collector
        tags: latest