name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Nodejs Packages
      run: cd ui && npm install
    - name: Build UI
      run: cd ui && npm run build
    - name: Build the Docker Image
      run: docker build . --tag crypto-collector:$(date +%s)
